spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: spring-cloud-config-server
---
spring:
  profiles: test
  application:
    name: spring-cloud-config-server-test